services:
  personal_blog:
    build: .
    container_name: personal_blog
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - FIGMA_ACCESS_TOKEN=figd_GEouIyLwqF1ZUNSXYbeouNmZ7oYc41ElxRwQZhDg